### ISSUE TITLE
Multiple Issues

### ISSUE THREAD

**Issue by amitiyer** [ictinnovations/ictdialer#11]
Hello,

I am observing a lot of issues while making a campaign and some settings are missing.

1. As mentioned on the Admin Guide of V3.0 there is no Account Management.
2. Freeswitch RPM (http://files.freeswitch.org/freeswitch-release-1-0.noarch.rpm) is not working well, The /var/run/freeswitch is missing and once we restart the server freeswitch never starts. I made the freeswitch work by installing the 1.6 RPM.
3. regarding the contacts, There is no sample CSV file, When i click on download i receive a file without any extension, (untitled) and when i open it in excel / spreadsheet program i get 2 lines with different parameters.
4. when i upload an IVR, it does not show the length / Type and when i download the uploaded IVR again it gets downloaded without the extension as (untitled)
5. When i start the Voice Campaign the transmission shows processing but i get nothing on the fs_cli nor does my provider get any hits.
6. Cannot change the admin password or email from the web-interface. 

Can you please check all these bugs ? Also i havent tested SMS / FAX / Email. Still stuck on the Campaign.

**Comment by ppwicho** [comment]
**When i start the Voice Campaign the transmission shows processing but i get nothing on the fs_cli nor does my provider get any hits.**   +1

**Comment by amitiyer** [comment]
Hello,

Did you get a change to look at these issues ?

**Comment by misua** [comment]
i wanted a campaign that just dials out. not playing some weird .wav file before the conversation starts. is that possible?

**Comment by amitiyer** [comment]
Hi,

are the issues solved ?

**Comment by ICTKashif** [comment]
Hi All,

We have released new version of ICTDialer, Please download ICTDialer from this link " http://www.ictdialer.org/installation-guide "

**Comment by amitiyer** [comment]
Hello Kashif,

I have installed the new version and after reboot, Freeswitch does not start

**Comment by ICTKashif** [comment]
Please run following command

`service freeswitch restart
`
if not work then Stop / Kill freeswitch process and run this command

`freeswitch -nc (for background)
`

**Comment by amitiyer** [comment]
Let me try that and get back to you.

**Comment by amitiyer** [comment]
![image](https://user-images.githubusercontent.com/25080311/59681043-9507b680-91f0-11e9-8d96-a8902a0d283d.png)

**Comment by ICTKashif** [comment]
Please run following commands

`ps -A | grep freeswitch`

result following
pid_number 00:27:42 freeswitch

```
kill -9 pid_number
freeswitch -nc
```

**Comment by amitiyer** [comment]
Freeswitch is not running, there is no process for the freeswitch.

**Comment by simplesunny** [comment]
I am getting this
[root@IP ~]# freeswitch -nc
5844 Backgrounding.

**Comment by simplesunny** [comment]
and after starting the service 

[root@1 ~]# service freeswitch restart
Restarting freeswitch (via systemctl):  Job for freeswitch.service failed because a configured resource limit was exceeded. See "systemctl status freeswitch.service" and "journalctl -xe" for details.
                                                           [FAILED]
[root@98 ~]# systemctl status freeswitch
● freeswitch.service - SYSV: Starts and stops the freeswitch server daemon
   Loaded: loaded (/etc/rc.d/init.d/freeswitch; bad; vendor preset: disabled)
   Active: failed (Result: resources) since Thu 2019-06-27 06:45:53 UTC; 11s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 6751 ExecStart=/etc/rc.d/init.d/freeswitch start (code=exited, status=0/SUCCESS)

Jun 27 06:45:53 1.1.1.1 systemd[1]: Starting SYSV: Starts and stops the freeswitch server daemon...
Jun 27 06:45:53 1.1.1.1 freeswitch[6751]: Starting freeswitch:
Jun 27 06:45:53 1.1.1.1 freeswitch[6751]: freeswitch is already running.[FAILED]
Jun 27 06:45:53 1.1.1.1 systemd[1]: PID file /usr/local/freeswitch/run/freeswitch.pid not readable (yet?) after start.
Jun 27 06:45:53 1.1.1.1 systemd[1]: Failed to start SYSV: Starts and stops the freeswitch server daemon.
Jun 27 06:45:53 1.1.1.1 systemd[1]: Unit freeswitch.service entered failed state.
Jun 27 06:45:53 1.1.1.1 systemd[1]: freeswitch.service failed.
